#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Validates the built Jekyll site (_site) with HTMLProofer.
#
# Scope (by design):
#   * Internal links, anchors and image/script sources ARE checked and will
#     fail the build. This is what catches broken links before they ship.
#   * Only the canonical (default-language) pages are checked. The per-language
#     mirrors under /es/, /fr/, /el/, ... are generated by the i18n plugin from
#     translation files that change continuously; gating on them would make CI
#     flaky for reasons unrelated to the change under review. Validating the
#     translated mirrors is tracked as follow-up work.
#   * External links are NOT checked here. Third-party sites go down for reasons
#     unrelated to this repo, which would make CI flaky and erode trust in it.
#     They can be checked in a separate, non-blocking job on a schedule.
#   * Missing `alt` attributes are NOT treated as failures. That is a separate
#     (and large) accessibility effort; folding it in here would turn this link
#     check into a blocked accessibility audit.
#
# BASELINE:
#   The URLs below are already broken on `master` as of the commit that
#   introduced this check. They are ignored so the check can be added without a
#   simultaneous mass content fix, and so it blocks only *newly* introduced
#   breakage ("ratchet"). They are catalogued upstream in:
#       <!-- TODO: replace with the tracking issue URL before opening the PR -->
#   Entries should be removed from this list as the underlying links are fixed.

require "html-proofer"

site_dir = ARGV[0] || "_site"

BASELINE_IGNORED_URLS = [
  # Blog posts tag themselves with tags that have no generated tag page yet
  # (the tag pages live in /blog/tags/*.md). Until those pages are added or the
  # tags are cleaned up, these links 404.
  %r{/blog/tags/(ccs|cryptography|dev|development|jamtis|kovri|magic|malware|monero|network upgrade|protocol|seraphis)\.html},

  # Dead cross-page anchors: the target page exists but the fragment does not.
  %r{/community/merchants/#exchanges},
  %r{/downloads/#windows},

  # Dead in-page anchors on the daemon RPC guide.
  /\A#getinfo\z/,
  /\A#getheight\z/,

  # Relative link written without a scheme, so it resolves to a local path that
  # does not exist (should point at https://cryptonote.org/whitepaper.pdf).
  %r{\Acryptonote\.org/whitepaper\.pdf\z},

  # Link to a release blog post that does not exist in _posts.
  %r{/2026/01/07/monero-0\.18\.4\.5-released\.html},

  # Placeholder self-link ("."") inside the vendored wallet-generator tool.
  /\A\.\z/,
].freeze

# The default language is served from the site root; every other configured
# language is mirrored under its own top-level directory. Skip those mirrors.
LOCALIZED_DIRS = %w[
  es it pl fr ar ru de nl pt-br tr zh-cn zh-tw nb-no el
].freeze

IGNORED_FILES = [
  %r{/_?site/(#{LOCALIZED_DIRS.map { |d| Regexp.escape(d) }.join("|")})/},
].freeze

options = {
  disable_external: true,
  enforce_https: false,
  ignore_missing_alt: true,
  ignore_urls: BASELINE_IGNORED_URLS,
  ignore_files: IGNORED_FILES,
}

HTMLProofer.check_directory(site_dir, options).run
